@echo off
setlocal enabledelayedexpansion

set JLINK_PATH="C:\ST\STM32CubeIDE_1.18.1\STM32CubeIDE\plugins\com.st.stm32cube.ide.mcu.externaltools.jlink.win32_2.4.0.202501261557\tools\bin\JLink.exe"                                   
set BUILD_TOOL_DIR=%~dp0
set "DEVICE=STM32F429IG"                                        
set "INTERFACE=JTAG"  
set "SPEED=4000"

@REM Show help information
if "%1"=="help" goto :show_help
if "%1"=="-h" goto :show_help
if "%1"=="--help" goto :show_help

@REM Parameter handling, select hex file to download
@REM If no parameter provided, use default hex file generated by Makefile
if "%1"=="" (
    set "HEX_FILE=%BUILD_TOOL_DIR%build\FreeRTOS_STM32F429.hex"
) else (
    set "HEX_FILE=%1"
)

REM Generate temporary J-Link command script
set COMMAND_FILE=%BUILD_TOOL_DIR%STM32_commands.jlink
(
    echo device %DEVICE%
    echo speed %SPEED%
    echo JTAGConf 0, 0
    echo if JTAG
    echo connect
    echo halt
    echo loadfile "!HEX_FILE!"
    echo reset
    echo go
    echo exit
) > "%COMMAND_FILE%"

@REM Download hex file to program flash
echo ============== Download !HEX_FILE! to STM32 ==============
@REM %JLINK_PATH% -CommandFile %JLINK_SCRIPT% -AutoConnect 1 -ExitOnError 1 -NoGui 1
%JLINK_PATH% -CommandFile %COMMAND_FILE% -AutoConnect 1 -ExitOnError 1 -NoGui 1

REM Clean up temporary files
del "%COMMAND_FILE%" 2>nul
if %errorlevel% equ 0 (
    echo download !HEX_FILE! success!
    exit /b 0
) else (
    echo download !HEX_FILE! failed!
    exit /b 1
)

goto :eof

:show_help
echo ===============================================================================
echo STM32 Hex File Download Script for J-Link
echo ===============================================================================
echo.
echo Usage:
echo   download.bat [hex_file] [options]
echo   download.bat help          - Show this help information
echo.
echo Arguments:
echo   hex_file                  Path to hex file to download (optional)
echo                             If not provided, uses: build\FreeRTOS_STM32F429.hex
echo.
echo Examples:
echo   download.bat                           - Download default hex file
echo   download.bat my_app.hex               - Download specific hex file
echo   download.bat ..\output\firmware.hex   - Download hex from parent directory
echo.
echo Configuration:
echo   Device: STM32F429IG
echo   Interface: JTAG
echo   Speed: 4000 kHz
echo.
echo Requirements:
echo   - J-Link driver and tools installed
echo   - STM32F429IG connected via JTAG
echo.
exit /b 0